# Use the Bitnami Spark base image with support of 'curl'
FROM bitnami/spark:3.3.0

# Switch to root to install curl
USER root

# Install curl and clean up to reduce image size
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Switch back to the non-root user
USER 1001

