version: '3'

services:

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./data:/usr/share/opensearch/data_import  # Mount local data directory
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch-node1

  data-loader:
    image: opensearchproject/opensearch:latest
    container_name: data-loader
    volumes:
      - ./data:/usr/share/opensearch/data_import  # Mount local data directory
    entrypoint: /usr/share/opensearch/data_import/load_data.sh
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data1:

