services:

  tonies-opensearch-storage:
    image: opensearchproject/opensearch:latest
    container_name: tonies-opensearch-storage
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
#      - plugins.security.disabled=true
#      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dwh-data1:/usr/share/opensearch/data
      - ./data:/usr/share/opensearch/data_import
    ports:
      # default port for OpenSearch HTTP
      - 9200:9200

      # OpenSearch Performance Analyzer plugin port
      - 9600:9600

    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/ -o /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  tonies-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: tonies-dashboards
    ports:
      # default port for OpenSearch Dashboards
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://tonies-opensearch-storage:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      tonies-opensearch-storage:
        condition: service_healthy

  tonies-data-loader:
    image: opensearchproject/opensearch:latest
    container_name: tonies-data-loader
    volumes:
      - ./data:/usr/share/opensearch/data_import
    entrypoint: /usr/share/opensearch/data_import/load_raw_data.sh
    depends_on:
      - tonies-opensearch-storage

  tonies-spark-master:
    # image: bitnami/spark:3.3.0
    # custom spark-master image is used in order to support curl and container healthcheck validation
    image: custom-spark-master:3.3.0
    container_name: tonies-spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080 | grep -q 'Spark Master'"]
      interval: 30s
      timeout: 10s
      retries: 5


  tonies-spark-worker:
    image: bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://tonies-spark-master:7077
    depends_on:
      - tonies-spark-master


  tonies-spark-etl:
    build: .
    container_name: tonies-spark-etl
    depends_on:
      tonies-data-loader:
        condition: service_started
      tonies-spark-master:
        condition: service_healthy
      tonies-spark-worker:
        condition: service_started
    restart: on-failure

volumes:
  dwh-data1:
